---
- name: Setup AzVolAutolity
  hosts: localhost
  vars_files:
  - ansible_vars.yml
  tasks:

    - name: Update System
      shell: |
        sudo apt-get update -y && sudo apt-get upgrade -y
      become: yes
      ignore_errors: yes

    # https://medium.com/@cmendibl3/installing-azure-cli-and-ansible-on-ubuntu-4fcabb7176b4
    - name: Install Azure CLI and kusto extension
      shell: |
        AZ_REPO=$(lsb_release -cs)
        echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | \ sudo tee /etc/apt/sources.list.d/azure-cli.list

        curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -

        sudo apt-get install apt-transport-https
        sudo apt-get update && sudo apt-get install azure-cli
        az extension add -n kusto
        az login --identity
      become: yes

    - name: "Install apt packages"
      apt:
        pkg: 
          - python3
          - python3-pip
          - git
          - clamav
          - build-essential
          - libssl-dev
          - libfuse2
          - regripper
          - reglookup
          - inotify-tools
          - dos2unix
        update_cache: yes
        state: present
      become: yes
      ignore_errors: yes

    - name: Update package lists
      ansible.builtin.apt:
        update_cache: yes
      become: yes 



    - name: Install pip packages
      ansible.builtin.pip:
        name: 
          - pyyaml
          - pandas
          - volatility3
          - azure-kusto-data
          - azure-kusto-ingest
          - azure-identity
          - azure-mgmt-kusto
          - azure-common
          - azure-mgmt-resource
          - azure-mgmt-eventgrid
          - azure-storage-blob
      become: yes

    - name: Adding plugins
      shell: |
        echo "https://github.com/f-block/volatility-plugins/blob/main/README.md"
        curl https://raw.githubusercontent.com/f-block/volatility-plugins/main/apisearch.py -o /usr/local/lib/python3.10/dist-packages/volatility3/framework/plugins/windows/apisearch.py
        curl https://raw.githubusercontent.com/f-block/volatility-plugins/main/imgmalfind.py -o /usr/local/lib/python3.10/dist-packages/volatility3/framework/plugins/windows/imgmalfind.py
        curl https://raw.githubusercontent.com/f-block/volatility-plugins/main/pe_parser.py -o /usr/local/lib/python3.10/dist-packages/volatility3/framework/plugins/windows/pe_parser.py
        curl https://raw.githubusercontent.com/f-block/volatility-plugins/main/pte_resolve.py -o /usr/local/lib/python3.10/dist-packages/volatility3/framework/plugins/windows/pte_resolve.py
        curl https://raw.githubusercontent.com/f-block/volatility-plugins/main/ptemalfind.py -o /usr/local/lib/python3.10/dist-packages/volatility3/framework/plugins/windows/ptemalfind.py
        curl https://raw.githubusercontent.com/f-block/volatility-plugins/main/ptenum.py -o /usr/local/lib/python3.10/dist-packages/volatility3/framework/plugins/windows/ptenum.py
        curl https://raw.githubusercontent.com/f-block/volatility-plugins/main/simple_pteenum.py -o /usr/local/lib/python3.10/dist-packages/volatility3/framework/plugins/windows/simple_pteenum.py
        curl https://raw.githubusercontent.com/f-block/volatility-plugins/main/swap_enum.py -o /usr/local/lib/python3.10/dist-packages/volatility3/framework/plugins/windows/swap_enum.py

        echo "https://github.com/Immersive-Labs-Sec/volatility_plugins/blob/main/README.md"
        curl https://raw.githubusercontent.com/Immersive-Labs-Sec/volatility_plugins/main/cobaltstrike/cobaltstrike.py -o /usr/local/lib/python3.10/dist-packages/volatility3/framework/plugins/windows/cobaltstrike.py
      become: yes
      ignore_errors: yes

    #####################
    # Blobfuse section
    #####################
    - name: Download Microsoft packages configuration for Ubuntu 20.04
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb
      become: yes
      ignore_errors: yes

    - name: Install Microsoft packages configuration
      ansible.builtin.apt:
        deb: /tmp/packages-microsoft-prod.deb
      become: yes
      ignore_errors: yes

    - name: Update package lists
      ansible.builtin.apt:
        update_cache: yes
      become: yes
      ignore_errors: yes

    - name: Install blobfuse
      ansible.builtin.apt:
        name: blobfuse
        state: present
      become: yes
      ignore_errors: yes

    - name: Create /mnt/ramdisk directory
      ansible.builtin.file:
        path: /mnt/ramdisk
        state: directory
        mode: '0755'
      become: yes
      ignore_errors: yes

    - name: Mount tmpfs to /mnt/ramdisk
      ansible.builtin.mount:
        path: /mnt/ramdisk
        src: tmpfs
        fstype: tmpfs
        opts: size=32g
        state: mounted
      become: yes
      ignore_errors: yes

    - name: Create /mnt/ramdisk/blobfusetmp directory
      ansible.builtin.file:
        path: /mnt/ramdisk/blobfusetmp
        state: directory
        mode: '0755'
      become: yes
      ignore_errors: yes

    - name: Change ownership of /mnt/ramdisk/blobfusetmp to root
      ansible.builtin.file:
        path: /mnt/ramdisk/blobfusetmp
        owner: root
        group: root
        state: directory
      become: yes
      ignore_errors: yes

    - name: Create mount directory for blobfuse
      ansible.builtin.file:
        path: "{{ dump_path }}"
        state: directory
        mode: '0755'
      become: yes
      ignore_errors: yes

    - name: Change ownership to root
      ansible.builtin.file:
        path: "{{ dump_path }}"
        owner: root
        group: root
        state: directory
      become: yes
      ignore_errors: yes

    - name: Create Blobfuse configuration file
      template:
        src: fuse_connection.cfg.j2
        dest: /etc/blobfuse.cfg
        owner: root
        group: root
        mode: '0600'
      become: yes

    - name: Mount Azure Blob Storage container
      ansible.builtin.shell: |
        mkdir -p /mnt/blobfusetmp
        blobfuse {{ dump_path }} --tmp-path=/mnt/blobfusetmp --config-file=/etc/blobfuse.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --log-level=LOG_INFO
      become: yes
      ignore_errors: yes

    - name: Change mode of VolatilityRunner script
      ansible.builtin.shell: chmod +x {{ project_path }}/bash_volatility_runner.sh
      become: yes
      ignore_errors: yes

    - name: Update clamav
      ansible.builtin.shell: freshclam
      become: yes
      ignore_errors: yes

    - name: Move any test samples to analysis folder
      ansible.builtin.shell: cp -r {{ project_path }}/sample/ /mnt/memorydumps
      become: yes
      ignore_errors: yes

    - name: Change mode of main.sh
      ansible.builtin.shell: chmod +x {{ project_path }}/main.sh
      become: yes
      ignore_errors: yes

    - name: Dos to Unix line endings
      ansible.builtin.shell: dos2unix {{ project_path }}/*.sh
      become: yes
      ignore_errors: yes

    - name: Run main.sh script cronjob every minute
      ansible.builtin.cron:
        name: "main"
        minute: "*"
        hour: "*"
        job: "{{ project_path }}/main.sh"
      become: yes
      ignore_errors: yes
